server:
  port: 8020
eureka:
  client:
    registerWithEureka: true #客户端功能
    fetchRegistry: true #客户端配置
    serviceUrl.defaultZone: http://localhost:8761/eureka/  #定义服务发访问地址

spring:
  application:
    name: mysql-phoenix
  datasource:
    dynamic:
      druid:
        filters: stat
        wall:
          multi-statement-allow: true
      datasource:
        master:
          username: root
          password: root
          url: jdbc:mysql://10.100.1.16:4306/dom?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=GMT
          driver-class-name: com.mysql.cj.jdbc.Driver
        dp:
          username: root
          password:
          url: jdbc:phoenix:dn3:2181
          driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver

# mybatis 相关配置
mybatis:
  configuration:
    # 是否打印sql语句 调试的时候可以开启
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl