server:
  port: 9901

spring:
  rabbitmq:
    host: dev.brd.bleem.site
    port: 5672
    username: admin
    password: bestway123
    virtual: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 5
  mqtt:
    host: tcp://172.22.1.136:1883
    username: admin
    password: root1234
    openFlag: open
    qos: 1
    connectionTimeout: 10
    keepAliveInterval: 10
    videoTimeOut: 5
    topic-prefix: /vehicle/
    client-id: ai

mqtt:
  host: tcp://172.22.1.136:1883
  username: admin
  password: root1234
  openFlag: open
  qos: 1
  connectionTimeout: 10
  keepAliveInterval: 10
  videoTimeOut: 5
  topic-prefix: /vehicle/
  client-id: ai

# Rabbit MQ
rabbitmq:
  bleemRibbit:
    enable: true
    exchange: bleem_ribbit_ex
    routingKey: bleem_ribbit_route
    queueKey: bleem_ribbit_queue
