server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://10.100.2.50:4306/batch-es?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&amp
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    rest:
      uris: http://10.100.1.140:9200
#是否开启本地存储
spring.data.elasticsearch.repositories.enable: true

spring.datasource.hikari.maximum-pool-size: 20
spring.datasource.hikari.minimum-idle: 5
# JPA 相关配置
spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql: false
######
# validate：验证创建数据库表结构
# create：重新创建数据库表结构，会导致数据库表数据丢失
# create-drop：重新创建数据库表结构，退出时删除表结构
# update：自动更新数据库结构
######
spring.jpa.hibernate.ddl-auto: validate

spring.jpa.hibernate.naming-strategy: cn.studyBoot.dao.strategy.UpperTableStrategy