server:
  port: 9001
eureka:
  instance:
    hostname: localhost #实例的主机名称
  client:
    registerWithEureka: true #客户端功能
    fetchRegistry: true #客户端配置
    serviceUrl.defaultZone: http://localhost:8761/eureka/  #定义服务发访问地址
  server:
    enable-self-preservation: false #禁用自我防护 防止服务驻留过长

spring:
  application:
    name: eureka-hazelcast-1
