server:
  port: 9090
eureka:
  client:
    registerWithEureka: true #客户端功能
    fetchRegistry: true #客户端配置
    serviceUrl.defaultZone: http://localhost:8761/eureka/  #定义服务发访问地址
spring:
  application:
    name: client-sentry
#  hazelcast:
#    config: classpath: hazelcast.xml
  cache:
    cache-names: outlimit
    type: caffeine
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s